[build]
  command = "pnpm build:web"
  publish = "apps/web/dist/client"

[build.environment]
  NODE_VERSION = "24"

[dev]
  command = "pnpm dev"
  port = 3000

[[redirects]]
  from = "/p/static/*"
  to = "https://us-assets.i.posthog.com/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/p/array/*"
  to = "https://us-assets.i.posthog.com/array/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/p/*"
  to = "https://us.i.posthog.com/:splat"
  status = 200
  force = true
