"""Event Consensus Protocol logic.

This module implements the logic to compare macro events from multiple LLM models
and promote them to the global timeline (long-term memory) if consensus is reached.
"""

import logging
from collections import defaultdict
from typing import Any
import numpy as np

from core.models import MacroEvent
from memory.store import add_memory, check_recent_memories
from memory.embeddings import get_embeddings_batch
from core.llm import synthesize_event

logger = logging.getLogger("engine")

def cosine_similarity(v1: list[float], v2: list[float]) -> float:
    """Computes the cosine similarity between two vectors."""
    if not v1 or not v2:
        return 0.0
    a = np.array(v1)
    b = np.array(v2)
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

async def process_consensus(events: list[MacroEvent], threshold: int = 2, sim_threshold: float = 0.85) -> list[dict]:
    """Process a list of macro events and identify consensus using semantic grouping,
    deduplication, and LLM synthesis.

    Args:
        events: All MacroEvent objects generated by all models.
        threshold: Minimum number of different models that must identify
            the same event for it to be promoted.
        sim_threshold: Cosine similarity threshold for semantic grouping.

    Returns:
        List of consensus events that were promoted to memory.
    """
    if not events:
        return []

    # 1. Batch generate embeddings for all event names
    event_names = [e.event_name for e in events]
    try:
        embeddings = get_embeddings_batch(event_names)
    except Exception as e:
        logger.error(f"Failed to get embeddings for semantic grouping: {e}")
        # Fallback to simple normalization if embeddings fail
        embeddings = [None] * len(events)

    # 2. Group events semantically
    # Each group is indexed by the representative event's index
    visited = [False] * len(events)
    groups = []

    for i in range(len(events)):
        if visited[i]:
            continue
        
        current_group = [events[i]]
        visited[i] = True
        
        # Compare with all subsequent events
        for j in range(i + 1, len(events)):
            if visited[j]:
                continue
            
            is_similar = False
            # If we have embeddings, use cosine similarity
            if embeddings[i] and embeddings[j]:
                similarity = cosine_similarity(embeddings[i], embeddings[j])
                if similarity >= sim_threshold:
                    is_similar = True
            # Fallback to string matching
            elif events[i].event_name.lower().strip() == events[j].event_name.lower().strip():
                is_similar = True
            
            if is_similar:
                current_group.append(events[j])
                visited[j] = True
        
        groups.append(current_group)

    consensus_reached = []

    # 3. Check each group for consensus
    for occurrences in groups:
        # Count unique models (providers + model names) that reported this event
        unique_models = set()
        for occ in occurrences:
            unique_models.add(f"{occ.model_provider}_{occ.model_name}")

        if len(unique_models) >= threshold:
            representative_name = occurrences[0].event_name
            logger.info(f"Consensus reached on semantic event group: '{representative_name}' ({len(unique_models)} models)")
            
            # Combine reasoning and determine majority impact
            impact_counts = defaultdict(int)
            reasonings = []
            source_ids = set()
            
            for occ in occurrences:
                impact_counts[occ.impact] += 1
                reasonings.append(occ.reasoning)
                source_ids.add(occ.source_id)

            majority_impact = max(impact_counts, key=impact_counts.get)
            
            # --- Temporal Deduplication ---
            # Check if a similar event was recently recorded
            if check_recent_memories(representative_name, threshold=sim_threshold):
                logger.info(f"Skipping promotion for '{representative_name}' - similar event found in recent history.")
                continue

            # --- LLM Synthesis ---
            # Create a professional name and summary
            synthesis = await synthesize_event(
                event_name=representative_name,
                impact=majority_impact,
                reasonings=reasonings
            )
            
            consensus_data = {
                "event_name": synthesis["name"],
                "impact": majority_impact,
                "reasoning": synthesis["summary"],
                "models_involved": list(unique_models),
                "source_ids": list(source_ids)
            }

            # 4. Promote to long-term memory
            memory_content = (
                f"MARKET EVENT: {consensus_data['event_name']} | "
                f"IMPACT: {consensus_data['impact']} | "
                f"SUMMARY: {consensus_data['reasoning']}"
            )
            
            success = add_memory(
                content=memory_content,
                metadata={
                    "type": "consensus_event",
                    "event_name": consensus_data['event_name'],
                    "impact": consensus_data['impact'],
                    "source_ids": consensus_data['source_ids'],
                    "raw_name": representative_name
                }
            )

            if success:
                consensus_reached.append(consensus_data)
                logger.info(f"Promoted synthesized consensus event: {consensus_data['event_name']}")
            else:
                logger.error(f"Failed to promote consensus event: {consensus_data['event_name']}")

    return consensus_reached
