import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from core.config import logger
from core.db import get_supabase_client
from tasks.predictor_autoresearch import calculate_baseline_score


def realign_predictor_baselines(client=None, dry_run: bool = True) -> dict:
    """Recalculate historical SECTOR_PREDICTOR_PROMPT scores using the modern formula

    and set up the true best-performing prompt variant as the new baseline.
    """
    if client is None:
        client = get_supabase_client()

    # 1. Fetch all evaluated sector predictions
    preds_resp = client.table("sector_predictions").select("*").eq("status", "evaluated").execute()
    all_preds = preds_resp.data or []

    # 2. Fetch all SECTOR_PREDICTOR_PROMPT experiments
    exp_resp = (
        client.table("prompt_experiments")
        .select("*")
        .eq("prompt_name", "SECTOR_PREDICTOR_PROMPT")
        .order("created_at")
        .execute()
    )
    experiments = exp_resp.data or []

    if not experiments:
        logger.warning("No SECTOR_PREDICTOR_PROMPT experiments found in database.")
        return {"dry_run": dry_run, "recalculated": [], "new_baseline_tag": None, "new_baseline_score": None}

    recalculated = []
    active_exp = None
    best_score = -1.0
    best_variant_tag = None

    for exp in experiments:
        tag = exp["variant_tag"]
        status = exp.get("status")
        w_start = exp.get("week_start")
        w_end = exp.get("week_end")
        old_score = exp.get("metrics", {}).get("score") if exp.get("metrics") else None

        if status == "active":
            active_exp = exp
            continue

        # Window matching: predictions whose target_date falls within [w_start, w_end]
        window_preds = (
            [p for p in all_preds if p.get("target_date") and w_start <= p["target_date"] <= w_end]
            if w_start and w_end
            else []
        )

        # Fallback to predictions generated by this prompt if window predictions are empty
        if not window_preds:
            window_preds = [p for p in all_preds if p.get("prompt_tag") == tag]

        new_score = calculate_baseline_score(window_preds) if window_preds else None

        recalculated.append(
            {
                "id": exp["id"],
                "variant_tag": tag,
                "old_status": status,
                "old_score": old_score,
                "new_score": new_score,
                "prediction_count": len(window_preds),
            }
        )

        if new_score is not None and new_score > best_score:
            best_score = new_score
            best_variant_tag = tag

    logger.info(f"Realigned baseline candidate: {best_variant_tag} with score {best_score:.4f} (dry_run={dry_run})")

    if not dry_run:
        for item in recalculated:
            tag = item["variant_tag"]
            new_score = item["new_score"]
            old_status = item["old_status"]

            # Determine new status
            if tag == best_variant_tag:
                new_status = "baseline"
            elif old_status == "baseline":
                new_status = "saved"
            else:
                new_status = old_status

            update_payload = {"status": new_status}
            if new_score is not None:
                update_payload["metrics"] = {"score": new_score}

            client.table("prompt_experiments").update(update_payload).eq("variant_tag", tag).execute()
            logger.info(f"Updated {tag}: status={new_status}, score={new_score}")

        # Update active prompt's parent_tag if active prompt exists
        if active_exp and best_variant_tag:
            client.table("prompt_experiments").update({"parent_tag": best_variant_tag}).eq(
                "variant_tag", active_exp["variant_tag"]
            ).execute()
            logger.info(f"Re-pointed active variant {active_exp['variant_tag']} parent to {best_variant_tag}")

    return {
        "dry_run": dry_run,
        "recalculated": recalculated,
        "new_baseline_tag": best_variant_tag,
        "new_baseline_score": best_score,
    }


def main():
    parser = argparse.ArgumentParser(description="Realign sector predictor baseline scores and ratchet.")
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Apply database updates. Default is dry-run mode.",
    )
    args = parser.parse_args()

    dry_run = not args.apply
    mode_str = "DRY RUN" if dry_run else "APPLYING TO DATABASE"
    print(f"=== SECTOR PREDICTOR BASELINE REALIGNMENT ({mode_str}) ===")

    result = realign_predictor_baselines(dry_run=dry_run)

    print("\nRecalculated Prompt Variants:")
    for r in result["recalculated"]:
        old_s = f"{r['old_score']:.4f}" if r["old_score"] is not None else "None"
        new_s = f"{r['new_score']:.4f}" if r["new_score"] is not None else "None"
        is_best = " ★ NEW BASELINE" if r["variant_tag"] == result["new_baseline_tag"] else ""
        print(
            f"  • {r['variant_tag'][:22]:22} | Status: {r['old_status']:9} | Old: {old_s:7} -> New: {new_s:7} (n={r['prediction_count']}){is_best}"
        )

    print(f"\nResult: New Baseline = {result['new_baseline_tag']} with Score = {result['new_baseline_score']:.4f}")
    if dry_run:
        print("\n[NOTE] No database rows were modified. Run with --apply to commit updates.")


if __name__ == "__main__":
    main()
