-- Migration: Create decisions table for Step 7 attribution layer
-- Created: 2025-12-24

CREATE TABLE decisions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id TEXT NOT NULL,
    ticker TEXT NOT NULL,
    signal TEXT NOT NULL,
    confidence INTEGER NOT NULL,
    reasoning TEXT NOT NULL,
    model_provider TEXT NOT NULL,
    model_name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE decisions ENABLE ROW LEVEL SECURITY;

-- Policy to allow the service role full access
CREATE POLICY "Allow service role full access to decisions" ON decisions
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

-- Comment on table for documentation
COMMENT ON TABLE decisions IS 'Stores trading decisions generated by LLMs with source attribution.';
