from unittest.mock import MagicMock

import pytest

from tasks.realign_predictor_baseline import realign_predictor_baselines


@pytest.fixture
def mock_supabase_data():
    experiments = [
        {
            "id": "exp-1",
            "variant_tag": "sector-pred-baseline",
            "prompt_name": "SECTOR_PREDICTOR_PROMPT",
            "week_start": "2026-06-07",
            "week_end": "2026-06-14",
            "status": "saved",
            "metrics": {"score": 52.0085},
            "parent_tag": None,
        },
        {
            "id": "exp-2",
            "variant_tag": "sector-pred-c60dab58",
            "prompt_name": "SECTOR_PREDICTOR_PROMPT",
            "week_start": "2026-07-19",
            "week_end": "2026-07-26",
            "status": "baseline",
            "metrics": {"score": 53.6723},
            "parent_tag": "sector-pred-baseline",
        },
        {
            "id": "exp-3",
            "variant_tag": "sector-pred-c6d96ec1",
            "prompt_name": "SECTOR_PREDICTOR_PROMPT",
            "week_start": "2026-08-17",
            "week_end": "2026-08-24",
            "status": "discarded",
            "metrics": {"score": 49.7945},
            "parent_tag": "sector-pred-c60dab58",
        },
        {
            "id": "exp-4",
            "variant_tag": "sector-pred-eb003dd8",
            "prompt_name": "SECTOR_PREDICTOR_PROMPT",
            "week_start": "2026-09-06",
            "week_end": "2026-09-13",
            "status": "active",
            "metrics": {},
            "parent_tag": "sector-pred-c60dab58",
        },
    ]

    predictions = [
        # Predictions generated by sector-pred-baseline (fallback because window has no predictions)
        {
            "id": "pred-0",
            "prompt_tag": "sector-pred-baseline",
            "prediction_date": "2026-06-14",
            "target_date": "2026-06-21",
            "status": "evaluated",
            "sector_percentile_score": 60.0,
            "worst_sector_percentile_score": None,
            "pair_percentile_score": 60.0,
            "brier_score": 0.25,
            "sector_sp_diff": 0.0,
        },
        # Predictions maturing during c60dab58's window (2026-07-19 to 2026-07-26)
        {
            "id": "pred-1",
            "prompt_tag": "sector-pred-c60dab58",
            "prediction_date": "2026-07-19",
            "target_date": "2026-07-26",
            "status": "evaluated",
            "sector_percentile_score": 50.0,
            "worst_sector_percentile_score": None,
            "pair_percentile_score": 50.0,
            "brier_score": 0.25,
            "sector_sp_diff": 0.0,
        },
        # Predictions maturing during c6d96ec1's window (2026-08-17 to 2026-08-24)
        {
            "id": "pred-2",
            "prompt_tag": "sector-pred-c6d96ec1",
            "prediction_date": "2026-08-17",
            "target_date": "2026-08-24",
            "status": "evaluated",
            "sector_percentile_score": 80.0,
            "worst_sector_percentile_score": 80.0,
            "pair_percentile_score": 80.0,
            "brier_score": 0.10,
            "sector_sp_diff": 2.0,
        },
    ]
    return experiments, predictions


def create_mock_supabase_client(experiments, predictions):
    client = MagicMock()

    class QueryMock:
        def __init__(self, table_name):
            self.table_name = table_name
            self._filters = {}
            self._updates = None

        def select(self, *args, **kwargs):
            return self

        def eq(self, col, val):
            self._filters[col] = val
            return self

        def order(self, *args, **kwargs):
            return self

        def update(self, vals):
            self._updates = vals
            return self

        def execute(self):
            res = MagicMock()
            if self.table_name == "prompt_experiments":
                if self._updates is not None:
                    # Apply update in memory
                    for exp in experiments:
                        match = True
                        for k, v in self._filters.items():
                            if exp.get(k) != v:
                                match = False
                                break
                        if match:
                            exp.update(self._updates)
                    res.data = experiments
                else:
                    data = [
                        e
                        for e in experiments
                        if e.get("prompt_name") == self._filters.get("prompt_name", e.get("prompt_name"))
                    ]
                    res.data = data
            elif self.table_name == "sector_predictions":
                res.data = [p for p in predictions if p.get("status") == "evaluated"]
            return res

    client.table.side_effect = lambda name: QueryMock(name)
    return client


def test_realign_predictor_baselines_dry_run(mock_supabase_data):
    experiments, predictions = mock_supabase_data
    client = create_mock_supabase_client(experiments, predictions)

    result = realign_predictor_baselines(client=client, dry_run=True)

    assert result["dry_run"] is True
    assert result["new_baseline_tag"] == "sector-pred-c6d96ec1"
    assert result["new_baseline_score"] > 70.0
    # Dry run should NOT mutate experiments in DB
    c60 = next(e for e in experiments if e["variant_tag"] == "sector-pred-c60dab58")
    assert c60["status"] == "baseline"
    assert c60["metrics"]["score"] == 53.6723


def test_realign_predictor_baselines_apply(mock_supabase_data):
    experiments, predictions = mock_supabase_data
    client = create_mock_supabase_client(experiments, predictions)

    result = realign_predictor_baselines(client=client, dry_run=False)

    assert result["dry_run"] is False
    assert result["new_baseline_tag"] == "sector-pred-c6d96ec1"

    # Verify status and scores updated
    c60 = next(e for e in experiments if e["variant_tag"] == "sector-pred-c60dab58")
    assert c60["status"] == "saved"
    # Base: 50, Brier: 0.25 -> 50 - 12.5 = 37.5
    assert c60["metrics"]["score"] == pytest.approx(37.5)

    c6d = next(e for e in experiments if e["variant_tag"] == "sector-pred-c6d96ec1")
    assert c6d["status"] == "baseline"
    # Base: 80, Alpha: +2.0, Brier: 0.10 -> 82 - (0.10 * 50) = 77.0
    assert c6d["metrics"]["score"] == pytest.approx(77.0)

    # Verify active prompt parent_tag re-pointed to new baseline
    eb0 = next(e for e in experiments if e["variant_tag"] == "sector-pred-eb003dd8")
    assert eb0["parent_tag"] == "sector-pred-c6d96ec1"
    assert eb0["status"] == "active"
